[project]
name = "kgat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ucekay", email = "Ucekay@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = [
    "cyclopts>=4.1.0",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "pandas-stubs>=2.3.2.250926",
    "scikit-learn>=1.7.2",
    "scipy>=1.16.3",
    "torch>=2.9.0",
    "tqdm>=4.66.5",
]

[project.scripts]
kgat = "kgat.cli:app"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"
