[project]
name = "edc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=2.6.1",
    "peft>=0.17.1",
    "sentence-transformers>=5.1.2",
    "transformers>=4.57.1",
]
