[project]
name = "edc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.11.0",
    "bs4>=0.0.2",
    "datasets>=4.3.0",
    "evaluate>=0.4.6",
    "lxml>=6.0.2",
    "nervaluate>=1.1.0",
    "nltk>=3.9.2",
    "openai>=1.0.0",
    "peft>=0.17.1",
    "sentence-transformers>=5.1.2",
    "transformers>=4.57.1",
    "unidecode>=1.4.0",
]
