[project]
name = "edc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.11.0",
    "datasets>=4.3.0",
    "evaluate>=0.4.6",
    "peft>=0.17.1",
    "sentence-transformers>=5.1.2",
    "transformers>=4.57.1",
]
